# Generated by Django 5.0 on 2023-12-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en-us', 'English'), ('nl', 'Dutch')], default='en-us', max_length=5),
        ),
    ]
