# Generated by Django 5.0 on 2023-12-19 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='language',
        ),
    ]
