# Generated by Django 4.2.7 on 2023-12-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtype',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
